services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
    environment:
      - FLASK_ENV=development
      - SENTRY_DSN=${SENTRY_DSN}
      - PYTHONPATH=/app
    command: ["python", "-m", "app"]

