services:
  backend:
    build:
      context: ./backend # Le contexte de build est le dossier 'backend'
      dockerfile: docker/Dockerfile # <-- CORRECTION ICI : Chemin relatif au contexte de build
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app # Monte le dossier 'backend' du système hôte vers '/app' dans le conteneur.
    environment:
      - FLASK_ENV=development
      - SENTRY_DSN=${SENTRY_DSN}
    command: ["python", "-m", "backend.core.app"]