services:
  traefik:
    image: traefik:latest
    container_name: traefik-oracle
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - oracle-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/traefik-data:/data
    command:
      - "--log.level=DEBUG"
      - "--accessLog=true"
      - "--providers.docker=true"
      - "--providers.docker.network=oracle-network"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=0.0.0.0:80"
      - "--entryPoints.websecure.address=0.0.0.0:443"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.web.transport.respondingTimeouts.readTimeout=120s"
      - "--entryPoints.web.transport.respondingTimeouts.writeTimeout=120s"
      - "--entryPoints.web.transport.respondingTimeouts.idleTimeout=180s"
      - "--entryPoints.websecure.transport.respondingTimeouts.readTimeout=120s"
      - "--entryPoints.websecure.transport.respondingTimeouts.writeTimeout=120s"
      - "--entryPoints.websecure.transport.respondingTimeouts.idleTimeout=180s"
      - "--certificatesresolvers.myresolver.acme.email=lmaumau22@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/data/acme.json"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"

  backend:
    build: ./backend
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
      - GUNICORN_CMD_ARGS=--timeout 120 --workers 3
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:5000/api/geometry/icosahedron/initial",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`quantum-oracle-entropie.duckdns.org`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
    networks:
      - oracle-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`quantum-oracle-entropie.duckdns.org`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    networks:
      - oracle-network
    restart: unless-stopped

networks:
  oracle-network:
    external: true
