
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
      - GUNICORN_CMD_ARGS=--timeout 120 --workers 3
      # Ajoute ici d'autres variables d'environnement (SENTRY_DSN, SECRET_KEY, etc.)
    # Pas de volume en prod !
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/geometry/icosahedron/initial"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "app=oracle-backend"
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`quantum-oracle-entropie.duckdns.org`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web,websecure"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "app=oracle-frontend"
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`quantum-oracle-entropie.duckdns.org`)"
      - "traefik.http.routers.frontend.entrypoints=web,websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

networks:
  default:
    name: oracle-entropie-
