
services:
  traefik:
    image: traefik:latest
    container_name: traefik-oracle
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - oracle-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/traefik-data:/data
    command:
      - "--log.level=DEBUG"
      - "--accessLog=true"
      - "--providers.docker=true"
      - "--providers.docker.network=oracle-network"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=0.0.0.0:80"
      - "--entryPoints.websecure.address=0.0.0.0:443"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.web.transport.respondingTimeouts.readTimeout=120s"
      - "--entryPoints.web.transport.respondingTimeouts.writeTimeout=120s"
      - "--entryPoints.web.transport.respondingTimeouts.idleTimeout=180s"
      - "--entryPoints.websecure.transport.respondingTimeouts.readTimeout=120s"
      - "--entryPoints.websecure.transport.respondingTimeouts.writeTimeout=120s"
      - "--entryPoints.websecure.transport.respondingTimeouts.idleTimeout=180s"
      - "--certificatesresolvers.myresolver.acme.email=lmaumau22@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/data/acme.json"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"

networks:
  oracle-network:
    external: true
