services:
  backend:
    build: ./backend
    ports:
      - "8080:5000"
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app
      - GUNICORN_CMD_ARGS=--timeout 120 --workers 3
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
networks:
  default:
    name: oracle-entropie-
