services:
  backend:
    build:
      context: . # Contexte de construction est la racine du projet
      dockerfile: backend/docker/Dockerfile # <-- CORRECTION ICI
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app # Monte le dossier 'backend' du système hôte vers '/app' dans le conteneur.
    environment:
      - FLASK_ENV=development
      - SENTRY_DSN=${SENTRY_DSN}
    command: ["python", "-m", "backend.core.app"] # <-- CORRECTION ICI (nouveau chemin de app.py)
