services:
  frontend:
    build:
      context: .
      dockerfile: frontend/docker/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
  backend:
    build:
      context: .
      dockerfile: backend/docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    networks:
      - app-network
networks:
  app-network:
    driver: bridge