global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:5000']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100'] # À ajouter si vous configurez un node-exporter
