name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
      - name: Build frontend
        run: |
          cd frontend
          npm run build
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt
      - name: Test backend
        run: |
          cd backend
          python -m pytest
      - name: Build Docker images
        run: |
          docker-compose build --no-cache
      - name: Test Docker services
        run: |
          docker-compose up -d
          sleep 10
          curl -f http://localhost:3000
          curl -f http://localhost:5000/geometry/spiral/initial
      - name: Push to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker-compose push